In [1]:
import torch

In [2]:
torch.tensor([1,2], dtype=torch.float32)

tensor([1., 2.])

In [3]:
torch.logspace(1, 5, steps=2, base=2)

tensor([ 2., 32.])

In [4]:
a = torch.randperm(25)

In [5]:
a.view(5, 5)

tensor([[10, 15, 19,  0, 18],
        [ 6, 12,  4,  5,  9],
        [20, 23,  8, 11, 13],
        [14,  7,  3, 21, 16],
        [22,  1,  2, 24, 17]])

In [6]:
a = torch.zeros(2, 3, 4)

In [7]:
a

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
torch.concat([a, a], 0)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
torch.concat([a, a], 1)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
torch.concat([a, a], 2)

tensor([[[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]]])

In [11]:
a

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
a = torch.randperm(9)

In [13]:
a = a.view(3,3)

In [14]:
a

tensor([[7, 4, 0],
        [6, 3, 1],
        [8, 5, 2]])

In [15]:
a.gather(0, torch.LongTensor([[0,1,2]]))

tensor([[7, 3, 2]])

In [16]:
a = torch.diag(torch.tensor([1, 2, 3], dtype=torch.double))
a

tensor([[1., 0., 0.],
        [0., 2., 0.],
        [0., 0., 3.]], dtype=torch.float64)

In [19]:
L_complex, V_complex = torch.linalg.eig(a)

In [20]:
L_complex

tensor([1.+0.j, 2.+0.j, 3.+0.j], dtype=torch.complex128)

In [21]:
V_complex

tensor([[1.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 1.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 1.+0.j]], dtype=torch.complex128)